const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    genre: "Fiction",
    rating: 4.8,
    pages: 281,
    cover: "images/To-Kill-a-Mockingbird.jpg",
    description: "A young girl grows up in the American South and witnesses her father defend a Black man accused of a crime, learning powerful lessons about justice, prejudice, and empathy.",
    images_Author: "author-images/Harper-Lee.jpg",
    about_author: "Harper Lee was an American novelist widely known for her 1960 Pulitzer Prize-winning novel, To Kill a Mockingbird. Her work is celebrated for its deep insights into morality, social injustice, and racial inequality in the American South."
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    year: 1949,
    genre: "Dystopian",
    rating: 4.7,
    pages: 328,
    cover: "images/1984.jpg",
    description: "In a totalitarian future, a man struggles against a regime that controls truth, thought, and individuality through constant surveillance and propaganda.",
    images_Author: "author-images/George-Orwell.jpg",
    about_author: "George Orwell, born Eric Arthur Blair, was an English novelist, essayist, and critic. He is best known for his sharp political commentary, particularly in '1984' and 'Animal Farm,' which remain essential critiques of totalitarianism."
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    genre: "Classic",
    rating: 4.4,
    pages: 180,
    cover: "images/The-Great-Gatsby.jpg",
    description: "A mysterious millionaire pursues a lost love in a glittering yet hollow world, revealing the illusions of wealth and the American Dream.",
    images_Author: "author-images/F. Scott-Fitzgerald.jpg",
    about_author: "F. Scott Fitzgerald was an American novelist and short story writer, best known for his depictions of the Jazz Age. His works explore themes of wealth, ambition, and the disillusionment inherent in the American Dream."
  },
  {
    id: 4,
    title: "Moby Dick",
    author: "Herman Melville",
    year: 1851,
    genre: "Adventure",
    rating: 4.1,
    pages: 635,
    cover: "images/Moby-Dick.jpg",
    description: "A sailor joins a dangerous voyage led by a captain obsessed with hunting a legendary white whale, leading to a tale of madness and revenge.",
    images_Author: "author-images/Herman-Melville.jpg",
    about_author: "Herman Melville was an American novelist and poet whose work became famous for its complex themes and symbolic depth. 'Moby Dick' is considered one of the greatest contributions to American literature."
  },
  {
    id: 5,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    genre: "Romance",
    rating: 4.6,
    pages: 279,
    cover: "images/Pride-and-Prejudice.jpg",
    description: "Elizabeth Bennet navigates love, class, and misunderstandings in a witty and insightful story about relationships and personal growth.",
    images_Author: "author-images/Jane-Austen.jpg",
    about_author: "Jane Austen was an English novelist known primarily for her six major novels, which interpret, critique, and comment upon the British landed gentry at the end of the 18th century."
  },
  {
    id: 6,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    genre: "Fantasy",
    rating: 4.8,
    pages: 310,
    cover: "images/The-Hobbit.jpg",
    description: "Bilbo Baggins embarks on an unexpected adventure with dwarves to reclaim treasure guarded by a dragon, discovering courage within himself.",
    images_Author: "author-images/J-R-R-Tolkien.jpg",
    about_author: "J.R.R. Tolkien was an English writer, poet, and philologist, best known as the author of 'The Hobbit' and 'The Lord of the Rings.' He is widely regarded as the father of modern high fantasy literature."
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    genre: "Fiction",
    rating: 4.2,
    pages: 277,
    cover: "images/The-Catcher-in-the-Rye.jpg",
    description: "A teenage boy wanders New York City, reflecting on life, identity, and his struggle with growing up and feeling disconnected.",
    images_Author: "author-images/J-D-Salinger.jpg",
    about_author: "J.D. Salinger was an American writer who gained worldwide fame after the publication of 'The Catcher in the Rye' in 1951. He remained notoriously reclusive throughout his later life, shunning publicity."
  },
  {
    id: 8,
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    genre: "Dystopian",
    rating: 4.5,
    pages: 311,
    cover: "images/Brave-New-World.jpg",
    description: "A futuristic society engineered for stability sacrifices individuality and freedom, raising questions about happiness and control.",
    images_Author: "author-images/Aldous-Huxley.jpg",
    about_author: "Aldous Huxley was an English writer and philosopher who wrote nearly 50 books. He is best known for his dystopian novel 'Brave New World,' which examines the conflict between technological progress and individual freedom."
  },
  {
    id: 9,
    title: "The Alchemist",
    author: "Paulo Coelho",
    year: 1988,
    genre: "Philosophical",
    rating: 4.3,
    pages: 208,
    cover: "images/The-Alchemist.jpg",
    description: "A shepherd travels across deserts in search of treasure, learning about destiny, dreams, and listening to his heart.",
    images_Author: "author-images/Paulo-Coelho.jpg",
    about_author: "Paulo Coelho is a Brazilian lyricist and novelist. He is best known for 'The Alchemist,' an international bestseller that follows a shepherd's journey toward his personal legend and self-discovery."
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    year: 1954,
    genre: "Fantasy",
    rating: 4.9,
    pages: 1178,
    cover: "images/The-Lord-of-the-Rings.jpg",
    description: "A group of heroes embark on a perilous journey to destroy a powerful ring that could bring darkness to the world.",
    images_Author: "author-images/J-R-R-Tolkien.jpg",
    about_author: "J.R.R. Tolkien was an English writer, poet, and philologist, best known as the author of 'The Hobbit' and 'The Lord of the Rings.' He is widely regarded as the father of modern high fantasy literature."
  },
  {
    id: 11,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    year: 1997,
    genre: "Fantasy",
    rating: 4.9,
    pages: 309,
    cover: "images/Harry-Potter-and-the-Sorcerer's-Stone.jpg",
    description: "A young boy discovers he is a wizard and begins his journey at a magical school filled with friendship, danger, and mystery.",
    images_Author: "author-images/J-K-Rowling.jpg",
    about_author: "J.K. Rowling is a British author best known for writing the 'Harry Potter' series, which has gained worldwide attention, won multiple awards, and sold more than 600 million copies."
  },
  {
    id: 12,
    title: "The Da Vinci Code",
    author: "Dan Brown",
    year: 2003,
    genre: "Thriller",
    rating: 4.1,
    pages: 489,
    cover: "images/The-Da-Vinci-Code.jpg",
    description: "A symbologist uncovers hidden secrets within famous artworks while being pursued in a high-stakes conspiracy.",
    images_Author: "author-images/Dan-Brown.jpg",
    about_author: "Dan Brown is an American author of thriller novels. He is best known for his 'Robert Langdon' series, which often features themes of cryptology, religious symbolism, and historical conspiracy."
  },
  {
    id: 13,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    year: 2008,
    genre: "Dystopian",
    rating: 4.6,
    pages: 374,
    cover: "images/The-Hunger-Games.jpg",
    description: "In a dystopian society, a young girl fights for survival in a deadly televised competition.",
    images_Author: "author-images/Suzanne-Collins.jpg",
    about_author: "Suzanne Collins is an American television writer and novelist, most famous for 'The Hunger Games' trilogy. Her work often addresses themes of war, survival, and the impact of media on society."
  },
  {
    id: 14,
    title: "The Book Thief",
    author: "Markus Zusak",
    year: 2005,
    genre: "Historical",
    rating: 4.7,
    pages: 552,
    cover: "images/The-Book-Thief.jpg",
    description: "A young girl in Nazi Germany finds comfort in stealing books and sharing stories during a time of war.",
    images_Author: "author-images/Markus-Zusak.jpg",
    about_author: "Markus Zusak is an Australian writer known for 'The Book Thief' and 'I Am the Messenger.' His writing style is often praised for its unique narrative voices and profound emotional impact."
  },
  {
    id: 15,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    year: 1847,
    genre: "Classic",
    rating: 4.5,
    pages: 500,
    cover: "images/Jane-Eyre.jpg",
    description: "An orphaned girl grows into a strong woman while facing love, hardship, and moral challenges.",
    images_Author: "author-images/Charlotte-Brontë.jpg",
    about_author: "Charlotte Brontë was an English novelist and poet, the eldest of the three Brontë sisters whose novels have become classics of English literature. Her writing is known for its strong characterization and emotional depth."
  },
  {
    id: 16,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    year: 1847,
    genre: "Classic",
    rating: 4.2,
    pages: 416,
    cover: "images/Wuthering-Heights.jpg",
    description: "A dark tale of passion and revenge unfolds on the Yorkshire moors, where love becomes destructive across generations.",
    images_Author: "author-images/Emily-Brontë.jpg",
    about_author: "Emily Brontë was an English novelist and poet who is best remembered for her only novel, 'Wuthering Heights.' It is considered a classic of English literature for its intense passion and unique structure."
  },
  {
    id: 17,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    genre: "Philosophical",
    rating: 4.6,
    pages: 671,
    cover: "images/Crime-and-Punishment.jfif",
    description: "A troubled student commits a crime and faces intense psychological turmoil as he struggles with guilt and morality.",
    images_Author: "author-images/Fyodor-Dostoevsky.jpg",
    about_author: "Fyodor Dostoevsky was a Russian novelist, short story writer, essayist, and philosopher. His literary works explore human psychology in the troubled political, social, and spiritual atmospheres of 19th-century Russia."
  },
  {
    id: 18,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    year: 2003,
    genre: "Drama",
    rating: 4.7,
    pages: 371,
    cover: "images/The-Kite-Runner.jpg",
    description: "A story of friendship and betrayal set in Afghanistan, following a man seeking redemption for his past actions.",
    images_Author: "author-images/Khaled-Hosseini.jpg",
    about_author: "Khaled Hosseini is an Afghan-born American novelist and physician. His debut novel, 'The Kite Runner,' became a global success, highlighting the complexities of Afghan history, culture, and personal redemption."
  },
  {
    id: 19,
    title: "The Fault in Our Stars",
    author: "John Green",
    year: 2012,
    genre: "Romance",
    rating: 4.4,
    pages: 313,
    cover: "images/The-Fault-in-Our-Stars.jpg",
    description: "Two teenagers with cancer fall in love, sharing a heartfelt journey about life, loss, and meaning.",
    images_Author: "author-images/John-Green.jpg",
    about_author: "John Green is an American author, vlogger, and producer. He is known for his young adult fiction novels, which often deal with serious life themes through the lens of poignant, witty, and relatable characters."
  },
  {
    id: 20,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    year: 1950,
    genre: "Fantasy",
    rating: 4.7,
    pages: 767,
    cover: "images/The-Chronicles-of-Narnia.jpg",
    description: "Children enter a magical world filled with talking animals, epic battles, and the struggle between good and evil.",
    images_Author: "author-images/C-S-Lewis.jpg",
    about_author: "C.S. Lewis was a British writer and academic. He is best known for his work in Christian apologetics and for his series of fantasy novels, 'The Chronicles of Narnia,' which are cherished for their allegorical storytelling."
  },
  {
    id: 21,
    title: "Animal Farm",
    author: "George Orwell",
    year: 1945,
    genre: "Political",
    rating: 4.6,
    pages: 112,
    cover: "images/Animal-Farm.jpg",
    description: "Farm animals rebel against their human owner, only to face a new tyranny that mirrors political corruption.",
    images_Author: "author-images/George-Orwell.jpg",
    about_author: "George Orwell, born Eric Arthur Blair, was an English novelist, essayist, and critic. He is best known for his sharp political commentary, particularly in '1984' and 'Animal Farm,' which remain essential critiques of totalitarianism."
  },
  {
    id: 22,
    title: "The Shining",
    author: "Stephen King",
    year: 1977,
    genre: "Horror",
    rating: 4.5,
    pages: 447,
    cover: "images/The-Shining.jpg",
    description: "A family’s winter stay in an isolated hotel turns terrifying as supernatural forces begin to take control.",
    images_Author: "author-images/Stephen-King.jpg",
    about_author: "Stephen King is an American author known for his horror, supernatural fiction, suspense, crime, and fantasy novels. He is one of the most prolific and popular authors of the modern era."
  },
  {
    id: 23,
    title: "Dracula",
    author: "Bram Stoker",
    year: 1897,
    genre: "Horror",
    rating: 4.3,
    pages: 418,
    cover: "images/Dracula.jpg",
    description: "A vampire count travels to England, spreading fear as a group attempts to stop his dark influence.",
    images_Author: "author-images/Bram-Stoker.jpg",
    about_author: "Bram Stoker was an Irish author best known for his 1897 Gothic horror novel 'Dracula.' His work established many of the conventions for modern vampire literature."
  },
  {
    id: 24,
    title: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    genre: "Sci-Fi",
    rating: 4.2,
    pages: 280,
    cover: "images/Frankenstein.jpg",
    description: "A scientist creates life, only to face the consequences when his creation becomes a misunderstood monster.",
    images_Author: "author-images/Mary Shelley.jpg",
    about_author: "Mary Shelley was an English novelist who wrote the Gothic novel 'Frankenstein; or, The Modern Prometheus.' Her work is often cited as the first true science fiction novel, exploring the ethics of creation."
  },
  {
    id: 25,
    title: "Dune",
    author: "Frank Herbert",
    year: 1965,
    genre: "Sci-Fi",
    rating: 4.8,
    pages: 412,
    cover: "images/Dune.jpg",
    description: "A young nobleman navigates politics, prophecy, and survival on a desert planet rich in a powerful resource.",
    images_Author: "author-images/Frank-Herbert.jpg",
    about_author: "Frank Herbert was an American science fiction writer best known for his 1965 novel 'Dune.' His work is celebrated for its intricate world-building and exploration of politics, ecology, and religion."
  },
  {
    id: 26,
    title: "The Road",
    author: "Cormac McCarthy",
    year: 2006,
    genre: "Post-Apocalyptic",
    rating: 4.3,
    pages: 287,
    cover: "images/The-Road.jpg",
    description: "A father and son journey through a bleak, post-apocalyptic world, holding onto hope and humanity.",
    images_Author: "author-images/Cormac-McCarthy .jpg",
    about_author: "Cormac McCarthy was an American novelist, playwright, and screenwriter. His work is known for its stark, sparse prose and exploration of violence, morality, and the resilience of the human spirit."
  },
  {
    id: 27,
    title: "Gone Girl",
    author: "Gillian Flynn",
    year: 2012,
    genre: "Thriller",
    rating: 4.2,
    pages: 422,
    cover: "images/Gone-Girl.jpg",
    description: "A man becomes the prime suspect in his wife’s disappearance, revealing dark secrets and twisted truths.",
    images_Author: "author-images/Gillian-Flynn.jpg",
    about_author: "Gillian Flynn is an American author and screenwriter. She has written three novels: 'Sharp Objects,' 'Dark Places,' and the globally successful 'Gone Girl,' all known for their dark themes and complex psychological tension."
  },
  {
    id: 28,
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    year: 2005,
    genre: "Crime",
    rating: 4.4,
    pages: 465,
    cover: "images/The-Girl-with-the-Dragon-Tattoo.jpg",
    description: "A journalist and a hacker team up to solve a decades-old disappearance tied to a powerful family.",
    images_Author: "author-images/Stieg-Larsson.jpg",
    about_author: "Stieg Larsson was a Swedish journalist and writer. He is best known for his 'Millennium' series, which gained international popularity for its gritty realism and social commentary."
  },
  {
    id: 29,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    year: 1996,
    genre: "Fantasy",
    rating: 4.8,
    pages: 694,
    cover: "images/A-Game-of-Thrones.jpg",
    description: "Noble families battle for power in a brutal fantasy world filled with political intrigue and looming danger.",
    images_Author: "author-images/George-R-R-Martin.jpg",
    about_author: "George R.R. Martin is an American novelist and short story writer. He is most famous for 'A Song of Ice and Fire,' a series of epic fantasy novels that are known for their sprawling scope and morally grey characters."
  },
  {
    id: 30,
    title: "The Martian",
    author: "Andy Weir",
    year: 2011,
    genre: "Sci-Fi",
    rating: 4.7,
    pages: 369,
    cover: "images/The-Martian.jpg",
    description: "An astronaut stranded on Mars must rely on science and ingenuity to survive and find a way home.",
    images_Author: "author-images/Andy-Weir.jpg",
    about_author: "Andy Weir is an American novelist and former software engineer. His debut novel, 'The Martian,' became a massive hit for its blend of hard science and humorous, survival-focused narrative."
  },
  {
    id: 31,
    title: "Life of Pi",
    author: "Yann Martel",
    year: 2001,
    genre: "Adventure",
    rating: 4.4,
    pages: 319,
    cover: "images/Life-of-Pi.jpg",
    description: "A boy survives a shipwreck and shares a lifeboat with a tiger, telling a story of faith and survival.",
    images_Author: "author-images/Yann-Martel.jpg",
    about_author: "Yann Martel is a Canadian writer best known for his Man Booker Prize-winning novel, 'Life of Pi.' His work often explores themes of faith, philosophy, and the nature of storytelling."
  },
  {
    id: 32,
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    year: 1969,
    genre: "Sci-Fi",
    rating: 4.2,
    pages: 275,
    cover: "images/Slaughterhouse-Five.jpg",
    description: "A soldier experiences time non-linearly after war, blending science fiction with reflections on trauma.",
    images_Author: "author-images/Kurt-Vonnegut.jpg",
    about_author: "Kurt Vonnegut was an American writer and humorist. Known for his satirical style and dark, often nihilistic, humor, his works like 'Slaughterhouse-Five' critique war, society, and the human condition."
  },
  {
    id: 33,
    title: "The Handmaid’s Tale",
    author: "Margaret Atwood",
    year: 1985,
    genre: "Dystopian",
    rating: 4.5,
    pages: 311,
    cover: "images/The-Handmaid’s-Tale.jpg",
    description: "In a totalitarian society, women are stripped of rights and forced into roles under strict control.",
    images_Author: "author-images/Margaret-Atwood.jpg",
    about_author: "Margaret Atwood is a Canadian poet, novelist, and literary critic. Her work, including 'The Handmaid's Tale,' is widely acclaimed for its exploration of gender, politics, and the consequences of authoritarianism."
  },
  {
    id: 34,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    genre: "Philosophical",
    rating: 4.4,
    pages: 254,
    cover: "images/The-Picture-of-Dorian-Gray.jpg",
    description: "A man remains physically young while his portrait ages, reflecting the consequences of vanity and corruption.",
    images_Author: "author-images/Oscar-Wilde.jpg",
    about_author: "Oscar Wilde was an Irish poet and playwright. Known for his biting wit and flamboyant style, his only novel, 'The Picture of Dorian Gray,' remains a profound examination of aesthetics, vanity, and morality."
  },
  {
    id: 35,
    title: "The Stranger",
    author: "Albert Camus",
    year: 1942,
    genre: "Existential",
    rating: 4.2,
    pages: 123,
    cover: "images/The-Stranger.jpg",
    description: "A detached man commits a senseless act and faces society’s judgment in a story about absurdity and meaning.",
    images_Author: "author-images/Albert-Camus.jpg",
    about_author: "Albert Camus was a French philosopher, author, and journalist. A key figure in existentialism and absurdism, his work explores the struggle of the individual in a universe that appears indifferent to human existence."
  },
  {
    id: 36,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    year: 1953,
    genre: "Dystopian",
    rating: 4.6,
    pages: 249,
    cover: "images/Fahrenheit-451.jpg",
    description: "In a future where books are banned, a fireman begins to question his role in burning knowledge.",
    images_Author: "author-images/Ray-Bradbury.jpg",
    about_author: "Ray Bradbury was an American writer who wrote in many genres, including fantasy, science fiction, and horror. He is best known for his novel 'Fahrenheit 451,' a powerful defense of literature and independent thought."
  },
  {
    id: 37,
    title: "The Odyssey",
    author: "Homer",
    year: -700,
    genre: "Epic",
    rating: 4.3,
    pages: 541,
    cover: "images/The-Odyssey.jpg",
    description: "A hero journeys home after war, facing monsters, gods, and trials over many years.",
    images_Author: "author-images/Homer.jpg",
    about_author: "Homer is the semi-legendary ancient Greek author of the 'Iliad' and the 'Odyssey,' two epic poems that are the foundational works of ancient Greek literature."
  },
  {
    id: 38,
    title: "The Iliad",
    author: "Homer",
    year: -750,
    genre: "Epic",
    rating: 4.2,
    pages: 683,
    cover: "images/The-Iliad.jpg",
    description: "An epic tale of the Trojan War, focusing on heroism, anger, and the cost of conflict.",
    images_Author: "author-images/Homer.jpg",
    about_author: "Homer is the semi-legendary ancient Greek author of the 'Iliad' and the 'Odyssey,' two epic poems that are the foundational works of ancient Greek literature."
  },
  {
    id: 39,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    year: 1605,
    genre: "Classic",
    rating: 4.1,
    pages: 863,
    cover: "images/Don-Quixote.jpg",
    description: "A man sets out to revive chivalry, mistaking reality for fantasy in a humorous and profound journey.",
    images_Author: "author-images/Miguel-de-Cervantes.jpg",
    about_author: "Miguel de Cervantes was a Spanish writer who is widely regarded as the greatest writer in the Spanish language. His novel 'Don Quixote' is considered the first modern novel and a masterpiece of world literature."
  },
  {
    id: 40,
    title: "Les Misérables",
    author: "Victor Hugo",
    year: 1862,
    genre: "Historical",
    rating: 4.7,
    pages: 1463,
    cover: "images/Les-Misérables.jpg",
    description: "A former prisoner seeks redemption while being pursued by a relentless inspector in revolutionary France.",
    images_Author: "author-images/Victor-Hugo.jpg",
    about_author: "Victor Hugo was a French poet, novelist, and dramatist. A major figure of the Romantic movement, his works, such as 'Les Misérables,' are celebrated for their social conscience and sweeping narrative power."
  },
  {
    id: 41,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    year: 1844,
    genre: "Adventure",
    rating: 4.8,
    pages: 1276,
    cover: "images/The-Count-of-Monte-Cristo.jpg",
    description: "A man escapes imprisonment and seeks revenge against those who betrayed him.",
    images_Author: "author-images/Alexandre-Dumas.jpg",
    about_author: "Alexandre Dumas was a French novelist. His works have been translated into many languages, and he is one of the most widely read French authors, known for his adventurous plots and historical settings."
  },
  {
    id: 42,
    title: "War and Peace",
    author: "Leo Tolstoy",
    year: 1869,
    genre: "Historical",
    rating: 4.5,
    pages: 1225,
    cover: "images/War-and-Peace.jpg",
    description: "A sweeping narrative of Russian society during the Napoleonic Wars, exploring love, fate, and history.",
    images_Author: "author-images/Leo-Tolstoy.jpg",
    about_author: "Leo Tolstoy was a Russian writer who is regarded as one of the greatest authors of all time. His novels 'War and Peace' and 'Anna Karenina' are pinnacles of realist fiction."
  },
  {
    id: 43,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: 1880,
    genre: "Philosophical",
    rating: 4.7,
    pages: 824,
    cover: "images/The-Brothers-Karamazov.jpg",
    description: "A complex story of family conflict, faith, and morality centered around three very different brothers.",
    images_Author: "author-images/Fyodor-Dostoevsky.jpg",
    about_author: "Fyodor Dostoevsky was a Russian novelist, short story writer, essayist, and philosopher. His literary works explore human psychology in the troubled political, social, and spiritual atmospheres of 19th-century Russia."
  },
  {
    id: 44,
    title: "Lolita",
    author: "Vladimir Nabokov",
    year: 1955,
    genre: "Classic",
    rating: 4.1,
    pages: 336,
    cover: "images/Lolita.jpg",
    description: "A controversial story told through the perspective of a man obsessed with a young girl.",
    images_Author: "author-images/Vladimir-Nabokovjpg.jpg",
    about_author: "Vladimir Nabokov was a Russian-American novelist, poet, and translator. He is known for his highly stylistic prose and complex structures, with 'Lolita' being his most famous and controversial work."
  },
  {
    id: 45,
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    year: 1952,
    genre: "Classic",
    rating: 4.3,
    pages: 127,
    cover: "images/The-Old-Man-and-the-Sea.jpg",
    description: "An aging fisherman battles a giant fish in a powerful story of perseverance and pride.",
    images_Author: "author-images/Ernest-Hemingway.jpg",
    about_author: "Ernest Hemingway was an American novelist, short-story writer, and journalist. His economical and understated style—which he termed the iceberg theory—had a strong influence on 20th-century fiction."
  },
  {
    id: 46,
    title: "The Giver",
    author: "Lois Lowry",
    year: 1993,
    genre: "Dystopian",
    rating: 4.3,
    pages: 240,
    cover: "images/The-Giver.jpg",
    description: "A boy discovers the hidden truths of his seemingly perfect society and begins to question everything.",
    images_Author: "author-images/Lois-Lowry.jpg",
    about_author: "Lois Lowry is an American writer of young adult literature. She is known for writing about difficult subject matters, and 'The Giver' remains one of the most significant works of dystopian children's fiction."
  },
  {
    id: 47,
    title: "Ready Player One",
    author: "Ernest Cline",
    year: 2011,
    genre: "Sci-Fi",
    rating: 4.6,
    pages: 374,
    cover: "images/Ready-Player-One.jpg",
    description: "In a virtual reality world, a teenager competes in a high-stakes quest filled with puzzles and pop culture references.",
    images_Author: "author-images/Ernest-Clin.jpg",
    about_author: "Ernest Cline is an American author, screenwriter, and spoken word artist. His novel 'Ready Player One' is a popular science fiction work that heavily utilizes 1980s pop culture nostalgia."
  },
  {
    id: 48,
    title: "The Maze Runner",
    author: "James Dashner",
    year: 2009,
    genre: "Dystopian",
    rating: 4.2,
    pages: 375,
    cover: "images/The-Maze-Runner.jpg",
    description: "A group of teens trapped in a mysterious maze must work together to survive and uncover the truth.",
    images_Author: "author-images/James-Dashner.jpg",
    about_author: "James Dashner is an American writer of speculative fiction. He is best known for his series 'The Maze Runner,' which has gained a significant following for its fast-paced action and suspense."
  },
  {
    id: 49,
    title: "Percy Jackson & The Lightning Thief",
    author: "Rick Riordan",
    year: 2005,
    genre: "Fantasy",
    rating: 4.7,
    pages: 377,
    cover: "images/Percy-Jackson-and-The-Lightning-Thief.jpg",
    description: "A boy discovers he is the son of a Greek god and embarks on a quest filled with mythological dangers.",
    images_Author: "author-images/Rick-Riordan.jpg",
    about_author: "Rick Riordan is an American author best known for his series 'Percy Jackson & the Olympians.' His work often brings Greek mythology into the modern world, making it accessible and engaging for younger readers."
  },
  {
    id: 50,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    year: 2019,
    genre: "Thriller",
    rating: 4.3,
    pages: 336,
    cover: "images/The-Silent-Patient.jpg",
    description: "A therapist becomes obsessed with uncovering why a woman stopped speaking after committing a shocking crime.",
    images_Author: "author-images/Alex-Michaelides.jpg",
    about_author: "Alex Michaelides is a British-Cypriot author and screenwriter. His debut psychological thriller, 'The Silent Patient,' became an international bestseller for its gripping plot and unexpected twists."
  }
];
